
import express from 'express';
import * as crypto from 'crypto';
import { GameEngine, BONUS_SPINS_AWARDED } from './GameEngine';

const app = express();
const port = process.env.PORT || 3000;

// Serve static files from the 'public' directory
app.use(express.static('public'));

app.use(express.json());

/**
 * This is the main SYNCHRONOUS entry point for the game logic.
 *
 * @param serverSeed The hexadecimal string generated by the server for this bet.
 * @param clientSeed A hexadecimal string provided by the player.
 * @param nonce A number that is incremented for each new bet from the player.
 * @returns The result of the spin.
 */
export const resolveBet = (
    serverSeed: string,
    clientSeed: string,
    nonce: number
) => {
    const engine = new GameEngine(serverSeed, clientSeed, nonce);
    const result = engine.resolveSpin(false);
    return {
        finalTotalWin: result.finalTotalWin,
        grid: result.grid,
        winningPaylines: result.winningPaylines,
        reel6Multiplier: result.reel6Multiplier,
        bonusTriggered: result.bonusTriggered,
    };
};

/**
* This function resolves a full bonus game round.
*/
export const resolveBonus = (serverSeed: string, clientSeed: string, nonce: number) => {
    let totalBonusWin = 0;
    const bonusSpins = [];
    for (let i = 0; i < BONUS_SPINS_AWARDED; i++) {
        const spinNonce = nonce + i + 1;
        const engine = new GameEngine(serverSeed, clientSeed, spinNonce);
        const spinResult = engine.resolveSpin(true); // 'true' for bonus spin
        totalBonusWin += spinResult.finalTotalWin;
        bonusSpins.push(spinResult);
    }
    return {
        totalBonusWin,
        bonusSpins,
    };
};


// API endpoint to play a round
app.post('/api/spin', (req, res) => {
    const { clientSeed, nonce } = req.body;

    if (!clientSeed || nonce === undefined) {
        return res.status(400).send({ error: 'clientSeed and nonce are required.' });
    }

    // In a real app, the server seed should be managed securely.
    const serverSeed = crypto.randomBytes(16).toString('hex');

    const result = resolveBet(serverSeed, clientSeed, nonce);

    // If a bonus is triggered, you might want to resolve it immediately
    // or have the client make a separate request.
    if (result.bonusTriggered) {
        const bonusResult = resolveBonus(serverSeed, clientSeed, nonce);
        // Add bonus results to the main result or handle as needed
        (result as any).bonusResult = bonusResult;
    }

    res.json(result);
});

app.listen(port, () => {
    console.log(`Server listening on port ${port}`);
});
